### ISSUE TITLE
yun sdk issues

### ISSUE THREAD

**Issue by cjevans76** [ParsePlatform/parse-embedded-sdks#13]
Is there a known issue with the yun SDK at the moment?  I've just followed the quick start guide withv 1.6.3 of the IDE for Windows and 1.0.0-1_ar71xx of the sdk.  No response from the calls to Parse.  The serial output looks like this:

Parse Starter Project

Response for saving a TestObject:
Test object id:
Push Installation ID:6868e0c2-c506-4dc7-9e3f-dd34075302d9

I can ping out from the board and some Temboo scripts worked fine, so it's definitely connected to the internet.  I've triple-checked the keys and they also look fine.
Any clues?

**Comment by mtl2034** [comment]
Unfortunately 1.6.2 and 1.6.3 have a bug in Bridge library that breaks put method. There is fix already https://github.com/arduino/Arduino/commit/8b019650d54c88c4b11778ad33fd5ab96ef61056 but it did not make it yet into official build.
You can either patch Bridge library if you want to use 1.6.3 or use 1.6.1. I hope that will resolve your issue.

**Comment by mtl2034** [comment]
The proper way to resolve this issue is to run Library Manager and update Bridge library from 1.0.0 to 1.0.1. To do this choose Sketch -> Include Libary -> Manage Libraries... . This will launch Library Manager, then find Bridge Library and press Update button.
