### ISSUE TITLE
Error declaring a global Parse client instance

### ISSUE THREAD

**Issue by Tkwon123** [ParsePlatform/parse-embedded-sdks#19]
I get a "'ParseClient' does not name a type" while trying to compile the quickstart example. I'm using the latest Arduino 1.6.3 IDE, and I've unpacked the parse.h and internal folder within the Arduino library. Any ideas? 

```
#include <Bridge.h>
#include <Parse.h>
/***** Quickstart of Parse Arduino Yún SDK *****/
// https://www.parse.com/apps/quickstart#embedded/arduinoyun

ParseClient client;

void setup() {

}

void loop() {

}
```

**Comment by mtl2034** [comment]
It looks like you are missing the library. Please make sure you did correctly step 6 from the quickstart. You should not add it manually but import it using this step. Also please do not forget to update the bridge library as 1.6.3 shipped with a bug: https://github.com/ParsePlatform/parse-embedded-sdks/issues/13.

**Comment by Tkwon123** [comment]
Ah sorry missed that. I updated bridge to 1.0.1 using the "manage libraries" option in the sketch dropdown and that seems to resolve the error. Thanks!
