### ISSUE TITLE
Duplicate push on embedded API during startup

### ISSUE THREAD

**Issue by d0n13** [ParsePlatform/parse-embedded-sdks#42]
I have the parse SDK on a RaspberryPI and I have setup my callback. All is working perfectly but when I restart the code on the Raspberry I get the last push I sent which was already processed. 

This happens every restart of the app on the Raspberry. Is this intended and do I need to write code to ignore it or do something else?

**Comment by mtl2034** [comment]
That issue should be fixed with the following commit: https://github.com/ParsePlatform/parse-embedded-sdks/commit/f2e4691715e0674e4a6c304b40fa1324d465aff4. Can you try the latest 1.0.1-rc3? You should not be getting repeated pushes on restart since that change.

**Comment by d0n13** [comment]
Hi mtl2034 
Yes, that solved my issue. Thank you
