### ISSUE TITLE
Embedded devices not detected for Push

### ISSUE THREAD

**Issue by RaedsLab** [ParsePlatform/parse-embedded-sdks#46]
There seems to be a bug when adding an embedded device, the web panel doesn’t seem to detect it and it keeps reporting that there are no devices.

**Comment by stanleyw** [comment]
Currently, we only support sending pushes to embedded devices via the REST API or from Cloud Code.  Please see https://www.parse.com/docs/rest/guide#push-notifications-sending-pushes and https://www.parse.com/docs/js/guide#push-notifications-sending-pushes

**Comment by ronaldyang** [comment]
One workaround: add a fake installation whose deviceType of "android" or " "ios". Then you should be able to send push to embedded device in console.

**Comment by mtl2034** [comment]
The support to send pushes to embedded devices has been added recently to the web panel.
