### ISSUE TITLE
OTA using SDK

### ISSUE THREAD

**Issue by muhammadhassan** [ParsePlatform/parse-embedded-sdks#59]
Can I do Over The Air update to the firmware using this SDK?

**Comment by francip** [comment]
No, the Parse Embedded SDK is intended only to give you easy access to the Parse.com platform.

However, if you upload the new version of the firmware as a File on Parse, you can use the Parse Embedded SDK to download it to the device. However, you will have to be careful with how you manage the available app memory on the device, and your app itself will be responsible for storing the new firmware to the permanent storage and doing the actual firmware update.
